version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: production
      DB_CONNECTION: pg
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: docker
      DB_PASSWORD: docker
      DB_DATABASE: projet_docker
      APP_KEY: "DlXmcnA8Lm1FOqc9Tg2iOfPIS-93ytJt"
      HOST: 0.0.0.0
      PORT: 3333
      LOG_LEVEL: info
      SESSION_DRIVER: cookie
    networks:
      - app-network
    depends_on:
      - db

  front:
    build:
      context: ./front
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      API_URL: http://backend:3333
    networks:
      - app-network

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: projet_docker
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
